version = 1

exclude_patterns = [
  "tests/*",
  "scripts/*"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/ianfhunter/GNOLL"

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "yapf"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true