/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gnoll_DiceNotationParser */

#ifndef _Included_org_gnoll_DiceNotationParser
#define _Included_org_gnoll_DiceNotationParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gnoll_DiceNotationParser
 * Method:    roll
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_gnoll_DiceNotationParser_roll
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
