name: "Manual: Memory Leaks"

on:
   workflow_dispatch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  valgrind:
    runs-on: ubuntu-latest
    name: Memory Leak detection
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lib Install
        run: |
            sudo apt-get install valgrind

      - name: Run Asan
        run: |
            make all DEBUG=2
            ./build/dice d20
      - name: Run Valgrind
        run: |
            make all DEBUG=1
            valgrind --leak-check=full ./build/dice d20
