name: "Binding Tests: GoLang"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: go install
      run: sudo apt install golang-go
    - name: make go
      run: make go
