name: "Test: OS Support"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install -r reqs/requirements.txt
    - name: make test
      run: |
        make all
        ./build/dice d20
        make install
        dice d100

  build_win:

    runs-on: windows-2022

    steps:
    - uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-22.04
        update: 'true'
        additional-packages:
          python3-dev
          bison
          flex
          python3-pip
          build-essential
          libssl-dev
          libffi-dev
          python3.10-venv

    - uses: actions/checkout@v3
    - name: test
      shell: wsl-bash {0}
      run: |
        make all
        ./build/dice d100

  build_mac:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make all
      - name: Test
        run: ./build/dice d20
