name: "Binding Tests"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:


  build_R:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - name: make r
      run: make r