name: "Binding Tests: Julia"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_julia:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: go install
      run: sudo apt install julia
    - name: make julia
      run: make julia
